[package]
name = "mini_db"
version = "0.1.0"
authors = ["TakeruTanaka <takeru.tt5672@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.1"

